services:
  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coderlab-challenge-test
    ports:
      - "5433:5432"
