services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coderlabs-challenge
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coderlabs-challenge-test
    ports:
      - "5433:5432"
volumes:
  data:
